# Generated by Django 5.0.1 on 2024-02-05 08:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 5, 8, 45, 43, 63570, tzinfo=datetime.timezone.utc)),
        ),
    ]
